# Generated by Django 2.0.7 on 2018-12-13 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0003_auto_20181212_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус прочтения поста', 'verbose_name_plural': 'Статус прочтения поста'},
        ),
        migrations.AddField(
            model_name='status',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.Posts', verbose_name='Пост'),
        ),
        migrations.AddField(
            model_name='status',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Прочитан'),
        ),
        migrations.AddField(
            model_name='status',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=250, null=True, verbose_name='Заголовок'),
        ),
    ]
